default_platform(:ios)
skip_docs

platform :ios do
  before_all do
    setup_ci if ENV['CI']
  end

  desc "Run tests"
  lane :test do
    scan(
      package_path: './',
      destination: 'platform=iOS Simulator,OS=18.0,name=iPhone 16 Pro',
      scheme: "UXKit",
      code_coverage: true,
      result_bundle: true,
    )
  end
end
