default_platform(:ios)

platform :ios do
  before_all do
    setup_ci if ENV['CI']
  end

  desc "Run tests"
  lane :test do
    scan(
      package_path: './',
      destination: 'platform=iOS Simulator,name=iPhone 14',
      scheme: "UXKit",
      code_coverage: true
    )
  end
end
