default_platform(:ios)

platform :ios do
  # https://docs.fastlane.tools/best-practices/continuous-integration/circle-ci/
  before_all do
    setup_circle_ci
  end

  desc "Run tests"
  lane :test do
    scan(
      package_path: './',
      destination: 'platform=iOS Simulator,name=iPhone 12',
      scheme: "UXKit",
      code_coverage: true
    )
  end
end
