name: CD
on:
  push:
    tags: ["v*"]
  release:
    types: [published]
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Authenticate private GitHub repos
        run: git config --global url."https://oauth2:${{ secrets.GH_ACCESS_TOKEN }}@github.com".insteadOf https://github.com
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Test
        run: bundle exec fastlane test
      - name: Create release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.github_token }}
          script: |
            const tag = process.env.GITHUB_REF.split('/').slice(-1)[0]

            try {
              await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: tag,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: tag,
              })
            }
            catch (error) {
              core.setFailed(error.message)
            }
  notify:
    name: Notify
    needs: [build]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: andrewscwei/telegram-action@v1.0.0
        with:
          success: ${{ needs.build.result == 'success' }}
          bot-token: ${{ secrets.TELEGRAM_DEVOPS_BOT_TOKEN }}
          chat-id: ${{ secrets.TELEGRAM_DEVOPS_CHAT_ID }}
