name: CI
on:
  pull_request:
  push:
    branches-ignore: [master]
jobs:
  build:
    name: Build
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: fastlane test
  notify:
    name: Notify
    needs: [build]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - uses: andrewscwei/telegram-action@v1
        with:
          success: ${{ needs.build.result == 'success' }}
          cancelled: ${{ needs.build.result == 'cancelled' }}
          bot-token: ${{ secrets.TELEGRAM_DEVOPS_BOT_TOKEN }}
          chat-id: ${{ secrets.TELEGRAM_DEVOPS_CHAT_ID }}
